config/routes.rb
ShopperEngine::Engine.routes.draw do
  scope 'cart' do
    get '/' => 'cart#index', as: 'cart'
    post 'add' => 'cart#add', as: 'add_to_cart'
    post 'update' => 'cart#update_quantity', as: 'cart_update_quantity'
    get 'submit' => 'cart#place', as: 'cart_submit'
  end
  resources :orders, only: [:index]
  resources :checkout, only: [:index, :show, :update]
end

app/models/shopper_engine/address.rb
module ShopperEngine
  class Address < ActiveRecord::Base
      belongs_to :country, class_name: 'ShopperEngine::Country'
      belongs_to :customer

      validates :address, presence: true
      validates :zipcode, presence: true, numericality: true
      validates :city, presence: true
      validates :phone, presence: true
      validates :country, presence: true

      def orders
          Order.where("billing_address_id = ? OR shipping_address_id = ?", self.id, self.id)
      end

  end
end

app/models/shopper_engine/cart.rb
module ShopperEngine
  class Cart < ShopperEngine::Order
    def add_item(product, quantity = 1)
        quantity = quantity.to_i unless quantity.is_a?(Fixnum)
        order_item = order_items.find_by({product: product})
        if (order_item)
           order_item.update_quantity(order_item.quantity + quantity)
           order_item.save
        else
            order_items.create({product: product, quantity: quantity, price: product.price * quantity})
        end
        update_price!
    end

    def update_quantity(order_item, quantity)
      quantity = quantity.to_i unless quantity.is_a?(Fixnum)
      if (quantity <= 0)
        order_item.delete
      else
        order_item.update_quantity(quantity)
        order_item.save
      end
      update_price!
    end


    def update_price!
        self.price = order_items.sum("price")
        save
    end

    def place!(customer)
      self.attributes = { customer: customer, state: SHIPPING, placed_at: Time.now }
      self.save!
    end

  end
end

app/models/shopper_engine/country.rb
module ShopperEngine
  class Country < ActiveRecord::Base
      validates :name, presence: true, uniqueness: true
  end
end

app/models/shopper_engine/credit_card.rb
module ShopperEngine
  class CreditCard < ActiveRecord::Base
      belongs_to :customer
      has_many :orders

      validates :number, presence: true, uniqueness: true, numericality: true, length: { is: 16 }
      validates :cvv, presence: true, numericality: true, length: { is: 3 }
      validates :expiration_month, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 12}
      validates :expiration_year, presence: true, numericality: { greater_than_or_equal_to: Date.current.year }
      validates :first_name, presence: true
      validates :last_name, presence: true
  end
end

app/models/shopper_engine/delivery.rb
module ShopperEngine
  class Delivery < ActiveRecord::Base
      validates :name, presence: true

      def short_description
        "#{name} (#{price}$)"
      end
  end
end

app/models/shopper_engine/order.rb
module ShopperEngine
  class Order < ActiveRecord::Base
      SHIPPING = 0
      FINISHED = 1

      belongs_to :customer
      belongs_to :credit_card, class_name: 'ShopperEngine::CreditCard'
      belongs_to :delivery, class_name: 'ShopperEngine::Delivery'

      has_many :order_items

      belongs_to :billing_address, class_name: ShopperEngine::Address
      belongs_to :shipping_address, class_name: ShopperEngine::Address

      scope :placed, -> { where("placed_at IS NOT NULL") }
      scope :shipping, -> { where("state = #{self::SHIPPING}") }
      scope :finished, -> { where("state = #{self::FINISHED}") }
  end
end

app/models/shopper_engine/order_item.rb
module ShopperEngine
  class OrderItem < ActiveRecord::Base
      belongs_to :product, polymorphic: true
      belongs_to :order, class_name: 'ShopperEngine::Order'

      def update_quantity (value)
        self.price = product.price * value
        self.quantity = value
      end

      validates :price, presence: true
      validates :quantity, presence: true
  end
end

app/controllers/shopper_engine/application_controller.rb
module ShopperEngine
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :set_cart

    def get_cart
      @cart
    end

    def set_cart
      initialize_cart if session[:cart_id].blank?
      begin
        @cart = ShopperEngine::Cart.find(session[:cart_id])
      rescue ActiveRecord::RecordNotFound
        initialize_cart
      end
    end

    def initialize_cart
      @cart = ShopperEngine::Cart.create
      session[:cart_id] = @cart.id
    end

    def current_user
      send("current_#{ShopperEngine::CONFIG[:devise_scope]}")
    end
  end
end

app/controllers/shopper_engine/cart_controller.rb
require_dependency "shopper_engine/application_controller"

module ShopperEngine
  class CartController < ApplicationController
    layout 'layouts/application'
    before_action :get_current_cart

    def index
    end

    def add
      @cart.add_item(find_product, cart_params[:quantity])
      flash.notice = 'Book added to your cart'
      redirect_to(action: :index)
    end

    def update_quantity
      order_item = @cart.order_items.find(cart_params[:id])
      @cart.update_quantity(order_item, params[:quantity])
      redirect_to(action: :index)
    end

    def place
      @cart.place!(current_user)
      flash[:notice] = "Your order has placed"
      session[:cart_id] = nil
      redirect_to(controller: :orders, action: :index)
    end

    private
    def cart_params
      params.permit([:id, :product_type, :product_id, :quantity])
    end

    def get_current_cart
      @cart = get_cart
    end

    def find_product
      class_name = ShopperEngine::PRODUCT_CLASSES.detect { |c| c == cart_params[:product_type] }
      class_name.camelize.constantize.find(cart_params[:product_id])
    end
  end
end

app/controllers/shopper_engine/checkout/addresses.rb
module ShopperEngine
  module Checkout
    class Addresses
      def initialize(cart:, type:, user:, params:)
        @user = user
        @cart = cart
        @type = type
        @params = params
      end

      def show
        get_user_addresses
        case @type
          when :billing
            @address = @cart.billing_address || @user.addresses.new
          when :shipping
            @address = @cart.shipping_address || @user.addresses.new
            @address = @user.addresses.new if @address == @cart.billing_address
        end
        get_address_editability
      end

      def update
        return skip_shipping if @params.permit(:skip_shipping)[:skip_shipping] == "true"
        unless address_selected?
          @address = @cart.send(address_type) || @user.addresses.new
          unless address_have_no_orders?
            @address = @user.addresses.new
          end
          @address.attributes = address_params
          @address.save!
          @cart.send("#{address_type}=", @address)
          @cart.save
        end
      end

      private

      def skip_shipping
        @cart.update shipping_address: @cart.billing_address
        @cart.save
      end

      def get_user_addresses
        @user_addresses = @user.addresses.all
      end

      def get_address_editability
        @address_editable = address_have_no_orders?(@address)
      end

      def address_have_no_orders?(address = nil)
        return false if address === nil
        return false unless address.id
        return address.orders.placed.count == 0
      end

      def address_selected?
        cart = @params.permit(cart: [address_type])
        if cart[:cart]
          @address = @user.addresses.find(cart[:cart][address_type])
          @cart.send("#{address_type}=", @address)
          @cart.save
        end
      end

      def address_params
        @params.require(:address).permit(:address, :zipcode, :city, :phone, :country_id)
      end

      def address_type
        "#{@type}_address"
      end

    end
  end
end

app/controllers/shopper_engine/checkout/confirmation.rb
module ShopperEngine
  module Checkout
    class Confirmation
      def initialize(cart:)
        @cart = cart
      end

      def show
        error_with_message :payment, "You must fill the credit card info" if @cart.credit_card.blank?
        error_with_message :delivery, "You must select the delivery method" if @cart.delivery.blank?
        error_with_message :shipping, "You must fill the shipping address" if @cart.shipping_address.blank?
        error_with_message :billing, "You must fill the billing address" if @cart.billing_address.blank?
      end

      private

      def error_with_message(step, message)
        @error = {
          step: step,
          message: message
        }
      end
    end
  end
end

app/controllers/shopper_engine/checkout/delivery.rb
module ShopperEngine
  module Checkout
    class Delivery
      def initialize(cart:, params:)
        @cart = cart
        @params = params
      end

      def show
      end

      def update
        @cart.update @params.require(:cart).permit(:delivery_id)
      end
    end
  end
end

app/controllers/shopper_engine/checkout/payment.rb
module ShopperEngine
  module Checkout
    class Payment
      def initialize(cart:, params:, user:)
        @user = user
        @cart = cart
        @params = params
      end

      def show
        @card_editable = card_have_no_orders?(@cart.credit_card)
        @credit_card = @card_editable ? @cart.credit_card : @user.credit_cards.new
        @user_credit_cards = @user.credit_cards.all
      end

      def update
        unless credit_card_selected?
          @credit_card = @cart.credit_card || @user.credit_cards.new
          unless card_have_no_orders?(@credit_card)
            @credit_card = @user.credit_cards.new
          end
          @credit_card.attributes = credit_card_params
          @credit_card.save!
          @cart.credit_card = @credit_card
          @cart.save
        end
      end

      private

      def credit_card_params
        @params.require(:credit_card).permit(
          :number, :cvv, :expiration_month, :expiration_year, :first_name, :last_name
        )
      end

      def card_have_no_orders?(card = nil)
        return false if card === nil
        return card.orders.placed.count == 0
      end

      def credit_card_selected?
        cart_params = @params.permit(cart: [:credit_card_id])
        if cart_params[:cart] && cart_params[:cart][:credit_card_id]
          @cart.update cart_params[:cart]
        end
      end
    end
  end
end

app/controllers/shopper_engine/checkout_controller.rb
module ShopperEngine
  class CheckoutController < ApplicationController
    include Wicked::Wizard
    include CartHelper
    layout "layouts/application"

    before_action :authenticate_customer!
    before_action :get_current_cart

    around_action :hande_errors

    steps :billing, :shipping, :delivery, :payment, :confirmation

    def initialize_steps
      @checkout_steps = {
        :billing => Checkout::Addresses.new(:cart => @cart, :user => current_user, :type => :billing, :params => params),
        :shipping => Checkout::Addresses.new(:cart => @cart, :user => current_user, :type => :shipping, :params => params),
        :delivery => Checkout::Delivery.new(:cart => @cart, :params => params),
        :payment => Checkout::Payment.new(:cart => @cart, :user => current_user, :params => params),
        :confirmation => Checkout::Confirmation.new(:cart => @cart)
      }
    end

    def show
      return redirect_to cart_path if @cart.order_items.empty?
      initialize_steps
      @checkout_steps[step].show
      render_wizard
    end

    def update
      initialize_steps
      @checkout_steps[step].update
      redirect_to next_wizard_path
    end

    private

    def render_wizard
      set_instance_variables!
      return redirect_with_message if @error
      super
    end

    def get_current_cart
      @cart = current_cart
    end

    def redirect_with_message
      flash[:alert] = @error[:message]
      redirect_to wizard_path(@error[:step])
    end

    def hande_errors
      begin
        yield
        rescue ActiveRecord::RecordInvalid => e
          flash.now[:alert] = e.record.errors.full_messages
          render_wizard
        rescue ActionController::ParameterMissing
          flash.now[:alert] = "You must select delivery method"
          render_wizard
      end
    end

    def set_instance_variables!
      @checkout_steps[step].instance_values.each { |k,v| instance_variable_set("@#{k}", v) }
    end
  end
end

app/controllers/shopper_engine/orders_controller.rb
module ShopperEngine
  class OrdersController < ApplicationController
    include ApplicationHelper
    layout 'layouts/application'
    before_action :authenticate_customer!

    def index
      @orders = current_user.orders.all
    end
  end
end

app/helpers/shopper_engine/application_helper.rb
module ShopperEngine
  module ApplicationHelper
    def method_missing(method, *args, &block)
      if (method.to_s.end_with?('_path') || method.to_s.end_with?('_url')) && main_app.respond_to?(method)
        main_app.send(method, *args)
      else
        super
      end
    end
  end
end

app/helpers/shopper_engine/cart_helper.rb
module ShopperEngine
  module CartHelper
    def add_to_cart_button(product)
      @product = product
      render partial: 'shopper_engine/cart/add_to_cart_button'
    end
    def current_cart
      if session[:cart_id]
        ShopperEngine::Cart.find(session[:cart_id])
      else
        create_cart
      end
    end

    def cart_total
      current_cart.price
    end
    private
    def create_cart
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
    end
  end
end

app/helpers/shopper_engine/checkout_helper.rb
module ShopperEngine
  module CheckoutHelper
    def wizard_progress
      wizard_steps.map do |s|
        classes = 'step'
        classes += (s == step) ? ' active' : ''
        { name: s, classes: classes }
      end
    end
  end
end

app/views/shopper_engine/checkout/_address_form.html.haml
= form_for address, url: {action: :update}, method: :put do |f|
  .form-group
    = f.label :address
    = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :zipcode
    = f.text_field :zipcode, class: 'form-control'
  .form-group
    = f.label :city
    = f.text_field :city, class: 'form-control'
  .form-group
    = f.label :phone
    = f.text_field :phone, class: 'form-control'
  .form-group
    = f.label :country
    = f.collection_select(:country_id, ShopperEngine::Country.all, :id, :name, {}, {class: 'form-control'})
  .form-group
    = f.submit @address_editable ? "Update" : "Save", class: 'btn btn-primary'

app/views/shopper_engine/checkout/_nav.html.haml
.btn-group.checkout-nav
  - wizard_progress.each do |step|
    = link_to step[:name].capitalize, wizard_path(step[:name]), {class: "btn btn-lg btn-default #{step[:classes]}"}

app/views/shopper_engine/checkout/billing.html.haml
%h1
  Addresses
= render partial: 'nav'
.row
  .col-sm-6
    .panel.panel-primary.address-panel
      .panel-heading
        %h4 Billing address
      .panel-body
        - if @user_addresses.present?
          %h4
            %strong Your addresses
          = form_for @cart, url: {action: :update} do |f|
            = f.collection_select(:billing_address, @user_addresses, :id, :address, {:selected => @cart.billing_address ? @cart.billing_address_id : nil})
            = f.submit("Select", {class: 'btn btn-primary'})
        %h4 Address info
        = render partial: 'address_form', locals: { address: @address }

app/views/shopper_engine/checkout/confirmation.html.haml
%h1
  Address
= render partial: 'nav'
.row
  .col-sm-6
    .panel.panel-primary.address-panel
      .panel-heading
        Billing address
      .panel-body
        = @cart.billing_address && @cart.billing_address.address
      .panel-heading
        Shipping address
      .panel-body
        = @cart.shipping_address && @cart.shipping_address.address
      .panel-heading
        Delivery
      .panel-body
        = @cart.delivery && @cart.delivery.name
      .panel-heading
        Payment
      .panel-body
        = @cart.credit_card && @cart.credit_card.number
  .col-sm-6
    .panel.panel-primary.address-panel
      .panel-heading
        Your cart
      .panel-body
        = render partial: 'shopper_engine/orders/table', locals: {order: @cart, editable: true }
%div
  =link_to 'Submit', cart_submit_path, {class: 'btn btn-primary', method: :get}

app/views/shopper_engine/checkout/delivery.html.haml
%h1
  Address
= render partial: 'nav'
.row
  .col-sm-6
    .panel.panel-primary.address-panel
      .panel-heading
        %h4 Delivery
      .panel-body
        = form_for @cart, url: {action: :update} do |f|
          = f.collection_radio_buttons(:delivery_id, ShopperEngine::Delivery.all, :id, :short_description) do |b|
            .radio
              = b.label(class: "radio_button") { b.radio_button(class: "radio_button") + b.text  }
          = f.submit("Save", {class: 'btn btn-primary'})

app/views/shopper_engine/checkout/payment.html.haml
%h1
  Address
= render partial: 'nav'
.row
  .col-sm-6
    .panel.panel-primary.address-panel
      .panel-heading
        %h4 Payment info
      .panel-body
        - if @user_credit_cards.present?
          %h4
            %strong Your credit cards
          = form_for @cart, url: {action: :update} do |f|
            = f.collection_select(:credit_card_id, @user_credit_cards, :id, :number)
            = f.submit("Select", {class: 'btn btn-primary'})
        %h4
          %strong Credit card info
        = form_for @credit_card, url: {action: :update}, method: :put do |f|
          .form-group
            = f.label :number
            = f.text_field :number, class: 'form-control'
          .form-group
            = f.label :cvv
            = f.text_field :cvv, class: 'form-control'
          .form-group
            = f.label :expiration_month
            = f.text_field :expiration_month, class: 'form-control'
          .form-group
            = f.label :expiration_year
            = f.text_field :expiration_year, class: 'form-control'
          .form-group
            = f.label :first_name
            = f.text_field :first_name, class: 'form-control'
          .form-group
            = f.label :last_name
            = f.text_field :last_name, class: 'form-control'
          .form-group
            = f.submit @card_editable ? "Update" : "Save", {class: 'btn btn-primary'}

app/views/shopper_engine/checkout/shipping.html.haml
%h1
  Addresses
= render partial: 'nav'
.row
  .col-sm-6
    .panel.panel-primary.address-panel
      .panel-heading
        - if @cart.billing_address.present?
          = form_tag checkout_path, method: :put, class: 'skip-shipping' do
            = hidden_field_tag :skip_shipping, true
            = submit_tag 'Use billing address', {class: 'btn btn-warning btn-default pull-right'}
        %h4 Shipping address
      .panel-body
        - if @user_addresses.present?
          %h4
            %strong Your addresses
          = form_for @cart, url: {action: :update} do |f|
            = f.collection_select(:shipping_address, @user_addresses, :id, :address, {:selected => @cart.shipping_address ? @cart.shipping_address.id.to_i : nil})
            = f.submit("Select", {class: 'btn btn-primary'})
        %h4 Address info
        = render partial: 'address_form', locals: { address: @address}